steps:
  - name: ansible-run
    command: 
      - 'docker build -f Dockerfile -t iotacafe/ansible-run:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER .'
      - 'docker push iotacafe/ansible-run:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER'
    plugins:
       docker#v2.0.0:
         image: "docker:latest"
         mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/docker/.docker:$HOME/.docker
    agents:
      queue: ops

