steps:
  - name: ansible-run
    command: 
      - "ls -al"
      - "docker build -f Dockerfile -t iotacafe/ansible-run:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER ."
      - "docker push iotacafe/ansible-run:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER"
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "docker:latest"
         volumes:
          - ".:/run"
         workdir: /run
    agents:
      queue: ops

