steps:
  - name: release-trinity-desktop
    command:
      - echo $$TRINITY_DESKTOP_DEPLOY_BUILDKITE_BUILD_ID && mkdir publish && buildkite-agent artifact download src/desktop/out/* publish --build $$TRINITY_DESKTOP_DEPLOY_BUILDKITE_BUILD_ID
      - find publish
    agents:
      queue: dev
    plugins:
      docker#v1.4.0:
        image: "docker:latest"
        shell: /bin/sh -c
        mount-buildkite-agent: true
        environment:
          - TRINITY_DESKTOP_DEPLOY_BUILDKITE_BUILD_ID
