steps:
  - name: release-trinity-desktop
    command:
      - mkdir tmp $$TRINITY_RELEASE_VERSION && buildkite-agent artifact download src/desktop/out/* tmp --build $$TRINITY_DESKTOP_DEPLOY_BUILDKITE_BUILD_ID && find tmp -type f -exec mv {} $$TRINITY_RELEASE_VERSION \;
    agents:
      queue: ops
    artifact_paths:
      - "$TRINITY_RELEASE_VERSION/*"
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
        image: "docker:latest"
        mount-buildkite-agent: true
        environment:
          - TRINITY_DESKTOP_DEPLOY_BUILDKITE_BUILD_ID
          - TRINITY_RELEASE_VERSION
