steps:
  - label: "Pushing to docker hub"
    commands:
      - mkdir target
      - sed -i '1,/# execution image/d' Dockerfile  
      - sed -i 's#--from=local_stage_build /iri/##g' Dockerfile
      - echo \$DOCKER_PASSWORD | docker login --username \$DOCKER_USERNAME --password-stdin
      - buildkite-agent artifact download target/iri-${IRI_VERSION:-$IRI_BUILD_NUMBER}.jar target/ --build $ARTIFACT_BUILDKITE_BUILD_ID
      - sha256sum target/iri-${IRI_VERSION:-$IRI_BUILD_NUMBER}.jar | cut -d " " -f 1 > target/SHA256SUM-${IRI_VERSION:-$IRI_BUILD_NUMBER}
      - docker build --no-cache -t sadjy/iri-dev:${IRI_GIT_TAG:-$IRI_BUILD_NUMBER} .
      - docker push sadjy/iri-dev:${IRI_GIT_TAG:-$IRI_BUILD_NUMBER}  
      - |
        case ${IRI_GIT_TAG:-$IRI_BUILD_NUMBER} in
          *'RELEASE' | *'RC'*)
            docker tag sadjy/iri-dev:${IRI_GIT_TAG:-$IRI_BUILD_NUMBER} sadjy/iri-dev:latest
            docker push sadjy/iri-dev:latest
            mv target $IRI_VERSION_NUMBER
          ;;
          *)
            mv target iri-dev
          ;;          
        esac        
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "docker"
        always-pull: true
        mount-buildkite-agent: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
    artifact_paths:
      - "${IRI_VERSION_NUMBER:-iri-dev}/iri-${IRI_VERSION:-$IRI_BUILD_NUMBER}.jar"
      - "${IRI_VERSION_NUMBER:-iri-dev}/SHA256SUM-${IRI_VERSION:-$IRI_BUILD_NUMBER}"
    agents:
      queue: aws-m5large



