steps:
  - label: "Pushing to docker hub - $IRI_BUILD_NUMBER"
    commands:
      - mkdir target
      - buildkite-agent artifact download target/iri-${IRI_BUILD_NUMBER}.jar target/ --build $ARTIFACT_BUILDKITE_BUILD_ID
      - sed -i '1,/# execution image/d' Dockerfile  
      - sed -i 's#--from=local_stage_build /iri/##g' Dockerfile
      - sha256sum target/iri-${IRI_BUILD_NUMBER}.jar > target/SHA256SUM-${IRI_BUILD_NUMBER}
      - docker login -u=\$DOCKER_USERNAME -p=\$DOCKER_PASSWORD
      - docker build -t sadjy/iri-dev:$IRI_BUILD_NUMBER -t sadjy/iri-dev:latest .
      - docker push sadjy/iri-dev:$IRI_BUILD_NUMBER
      - docker push sadjy/iri-dev:latest
      - |
        if [ ! -z "$IRI_GIT_TAG" ]; then
          case $IRI_GIT_TAG in
            *'RELEASE' | *'RC'*)
              docker tag sadjy/iri-dev:$IRI_BUILD_NUMBER sadjy/iri-dev:$IRI_GIT_TAG
              docker push sadjy/iri-dev:$IRI_GIT_TAG
              mkdir $IRI_VERSION
              cp target/iri-$IRI_BUILD_NUMBER.jar $IRI_VERSION/iri-$IRI_GIT_TAG.jar
              cp target/SHA256SUM-$IRI_BUILD_NUMBER $IRI_VERSION/SHA256SUM-$IRI_GIT_TAG                        
            ;;
            *)
              echo 'Nothing to do'
            ;;
          esac
        fi
      - ls -al
      - ls -al target
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "docker"
        always-pull: true
        mount-buildkite-agent: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /conf/docker/.docker:$HOME/.docker
        environment:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
    artifact_paths:
      - "$IRI_VERSION/iri-$IRI_GIT_TAG.jar"
      - "$IRI_VERSION/SHA256SUM-$IRI_GIT_TAG"
    agents:
      queue: aws-m5large

  - wait

  - trigger: iri-regression-tests-dev
    build:
      env:
        IRI_BUILD_NUMBER: $IRI_BUILD_NUMBER
        IRI_GIT_COMMIT: $IRI_GIT_COMMIT
        IRI_BUILDKITE_PULL_REQUEST_REPO: $IRI_BUILDKITE_PULL_REQUEST_REPO
        ARTIFACT_BUILDKITE_BUILD_ID: $ARTIFACT_BUILDKITE_BUILD_ID