steps:
  - label: ":hammer_and_wrench: Build for macOS platform"
    command:
      - "npm ci"
      - "npm run build"
      - "security unlock-keychain -p $$BUILDKITE_KEYCHAIN_PASSWORD BuildkiteKeychain.keychain && security set-key-partition-list -S apple-tool:,apple: -s -k $$BUILDKITE_KEYCHAIN_PASSWORD BuildkiteKeychain.keychain"
      - "./node_modules/.bin/electron-builder --mac --x64 --publish=never"
      - "security lock-keychain BuildkiteKeychain.keychain"
      - "cd out"
      - "for i in `ls seed-migration-tool*` ; do shasum -a 256 $$i | awk {'print $$1'} > $$i.sha256 ; done"
    agents:
      queue: mac
    artifact_paths:
      - "out/builder-effective-config.yaml"
      - "out/latest*"
      - "out/seed-migration-tool*"

  - label: ":hammer_and_wrench: Build for Linux platform"
    command:
      - "npm ci"
      - "npm run build"
      - "./node_modules/.bin/electron-builder --linux --x64 --publish=never"
      - "cd out"
      - "echo $$GPG_CONTACT_IOTA_ORG_PASSPHRASE | gpg --pinentry-mode loopback --batch --passphrase-fd 0 --armor --detach-sign --default-key contact@iota.org seed-migration-tool*.AppImage"
      - "for i in `ls seed-migration-tool*` ; do sha256sum $$i | awk {'print $$1'} > $$i.sha256 ; done"
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "iotacafe/trinity-desktop-ci:latest"
         always-pull: true
         shell: "/bin/sh -e -c"
         environment:
           - GPG_CONTACT_IOTA_ORG_PASSPHRASE
         mounts:
           - /conf/ssh:/root/.ssh
           - /conf/gnupg:/root/.gnupg
    agents:
      queue: ops
    artifact_paths:
      - "out/builder-effective-config.yaml"
      - "out/latest*"
      - "out/seed-migration-tool*"

  - label: ":hammer_and_wrench: Build for Windows platform"
    command:
      - "npm ci && npm run build && .\\node_modules\\.bin\\electron-builder --win --x64 --publish=never && mv out/latest* . && mv out/seed-migration-tool* ."
    agents:
      queue: ec2-win-t2medium
    artifact_paths:
      - "latest*"
      - "seed-migration-tool*"
