steps:
  - name: build-iri-oracle8
    command: 'docker build . -t iotacafe/iri-dev:$BUILDKITE_COMMIT .'
    plugins:
      docker#v1.4.0:
        image: "docker/latest"
    agents:
      queue: dev

