steps:
  - name: build-iri-oracle8
    command: 
      - 'docker build -f Dockerfile -t iotacafe/iri-dev:$BUILDKITE_BRANCH-${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER .'
      - 'docker push iotacafe/iri-dev:$BUILDKITE_BRANCH-${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER'
    plugins:
       docker#v1.4.0:
         image: "docker:latest"
         shell: "/bin/sh -e -c"
         mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/docker/.docker:$HOME/.docker
    agents:
      queue: ops

  - wait

  - trigger: "iri-regression-tests"
    build:
      env:
        IRI_BUILD_NUMBER: $BUILDKITE_BRANCH-${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER
