steps:
  - name: build-iri-oracle8
    command: 
      - 'docker build -f Dockerfile -t iotacafe/iri-dev:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER .'
      - 'docker push iotacafe/iri-dev:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER'
      - 'echo ${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER'
#      env:
#        GIT_COMMIT: '$(git rev-parse HEAD)'
    plugins:
       docker#v1.4.0:
         image: "docker:latest"
         shell: "/bin/sh -e -c"
    agents:
      queue: sdj

  - trigger: "iri-regression-tests"