steps:
  - name: build-iri-oracle8
    command: 'docker build -f Dockerfile -t iotacafe/iri-dev:$GIT_COMMIT .'
    plugins:
       docker#v1.3.0:
         image: "docker:latest"
    agents:
      queue: dev

