steps:
  - name: zeit-build-and-deploy
    command: 
      - |
        npm i -g --unsafe-perm now
        apt-get update && apt-get install -y rsync
        rm -rf docs && mkdir docs
        rm -rf tmp && mkdir -p tmp
        git clone https://github.com/iotaledger/documentation-markdown.git tmp/documentation-markdown
        cd tmp/documentation-markdown && rsync -av -m --include='**/*.md' --include='*/' --exclude='*' . ../../docs && cd ../../
        rm -rf tmp
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/src/config.staging.json src/config.json
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/now.staging.json now.json
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota deploy --force --docker -n documentation-web -m BK_JOB_ID=$BUILDKITE_JOB_ID
        NOW_SH_DEPLOYMENT_ID=$(now --platform-version 1 --token \$ZEIT_TOKEN --team iota ls -m BK_JOB_ID=$BUILDKITE_JOB_ID | grep documentation-web | awk {'print \$2'})
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota alias \$NOW_SH_DEPLOYMENT_ID documentation.iota.works
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "node:8.12-stretch"
         shell: "/bin/sh -e -c"
         environment:
          - ZEIT_TOKEN
    agents:
      queue: ops
