steps:
  - name: build-and-push-documentation-container
    command: 
      - cd documentation
      - rm -rf docs
      - docker build -f Dockerfile -t iotacafe/documentation:${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8} .
      - docker push iotacafe/documentation:${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "docker:latest"
         shell: "/bin/sh -e -c"
         mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/docker/.docker:$HOME/.docker
    agents:
      queue: ops
