steps:
  - label: ":pipeline: Run Trinity Mobile (PRs) pipeline"
    command:
      - "yarn"
      - "yarn deps:shared"
      - "yarn deps:mobile"
      - "cd src/mobile && yarn audit && cd ../.."
      - "yarn lint:mobile"
      - "cd src/mobile && yarn test && cd ../.."
      - "cd src/mobile && react-native bundle --entry-file index.js --platform android --bundle-output android/main.jsbundle --dev true"
    agents:
      queue: dev
    plugins:
      docker#v2.0.0:
        image: "iotacafe/trinity-mobile-ci:583b99c-3"
