steps:
  - label: ":pipeline: Run Trinity Mobile (PRs) pipeline"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/mobile && yarn && cd ../.."
      - "cd src/shared && yarn audit && cd ../mobile && yarn audit && cd ../.."
      - "yarn lint:shared && yarn lint:mobile"
      - "cd src/mobile && yarn test && cd ../.."
      - "cd src/mobile && react-native bundle --entry-file index.js --platform android --bundle-output android/main.jsbundle --dev true"
    agents:
      queue: dev
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
        image: "iotacafe/trinity-mobile-ci:583b99c-3"
