steps:
  - name: build-trinity-mobile-ci
    command: 
      - 'docker build -f Dockerfile -t iotacafe/trinity-mobile-ci:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER .'
      - 'docker push iotacafe/trinity-mobile-ci:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER'
      - 'docker tag iotacafe/trinity-mobile-ci:${GIT_COMMIT:0:7}-$BUILDKITE_BUILD_NUMBER iotacafe/trinity-mobile-ci:latest'
      - 'docker push iotacafe/trinity-mobile-ci:latest'
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "docker:latest"
         mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/docker/.docker:$HOME/.docker
    agents:
      queue: ops

