steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && node bugsnag.js"
      - "npm run build && ./node_modules/.bin/electron-builder -mwl"
    agents:
      queue: mac
    artifact_paths:
      - "out/builder-effective-config.yaml"
      - "out/latest*"
      - "out/trinity-desktop*"
