steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && node bugsnag.js"
      - "npm run build && electron-builder -mwl"
    agents:
      queue: mac
    env:
      WIN_CSC_LINK: "./cert.p12"

  - label: ":amazon-s3: Upload artifacts to Amazon S3"
    command:
      - "cd out"
      - "buildkite-agent artifact upload "builder-effective-config.yaml" s3://$S3_BUCKET/$BUILDKITE_JOB_ID"
      - "buildkite-agent artifact upload "latest*" s3://$S3_BUCKET/$BUILDKITE_JOB_ID"
      - "buildkite-agent artifact upload "trinity-desktop*" s3://$S3_BUCKET/$BUILDKITE_JOB_ID"
    agents:
      queue: mac
    env:
      S3_BUCKET: "bucket_name"
