steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && npm run build && node bugsnag.js"
      - "security unlock-keychain -p $$BUILDKITE_KEYCHAIN_PASSWORD BuildkiteKeychain.keychain && security set-key-partition-list -S apple-tool:,apple: -s -k $$BUILDKITE_KEYCHAIN_PASSWORD BuildkiteKeychain.keychain"
      - "npm run compile:mac"
      - "npm run compile:win"
      - "npm run compile:linux"
      - "security lock-keychain BuildkiteKeychain.keychain"
      - "cd out"
      - "echo $$GPG_CONTACT_IOTA_ORG_PASSPHRASE | gpg --pinentry-mode loopback --batch --passphrase-fd 0 --armor --detach-sign --default-key contact@iota.org trinity-desktop*.AppImage"
      - "for i in `ls trinity-desktop*` ; do shasum -a 256 $$i | awk {'print $$1'} > $$i.sha256 ; done"
    agents:
      queue: mac
    artifact_paths:
      - "src/desktop/out/builder-effective-config.yaml"
      - "src/desktop/out/latest*"
      - "src/desktop/out/trinity-desktop*"
