steps:
  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && node bugsnag.js"
      - "npm run build && electron-builder -mwl"
    agents:
      queue: mac
    env:
      WIN_CSC_LINK: "./cert.p12"
    artifact_paths:
      - "out/builder-effective-config.yaml"
      - "latest*"
      - "trinity-desktop*"
