steps:
  - name: push-to-sdjnet
    command: buildkite-agent artifact upload "/opt/bigting.txt" s3://sadjy-test/$BUILDKITE_JOB_ID
##    plugins:
##      docker#v1.4.0:
##        image: "sadjy/ansible-run" 
##        shell: "/bin/sh -e -c" 
##        environment:
#          - VAULT_TOKEN
##          - VAULT_ADDR
##          - SSH_CLIENT_SIGNER_ADDR
##          - SSH_HOST_SIGNER_ADDR
#          - VAULT_TOKEN_CREATE_ADDR
#          - BUILDKITE_COMMAND
##          - DOCKER_VAULT_TOKEN
##          - OP_NW

    agents:
      queue: sdj
#  - block: "Block 1"

#    name: push-to-spamnet
#    command: ansible-playbook -i hosts.ini site.yml --limit spamnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"

#  - wait

#  - name: push-to-devnet
#    command: ansible-playbook -i hosts.ini site.yml --limit devnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"

#  - block: "Push to mainnet: confirmation required."
#    prompt: "Push to mainnet?"

#  - name: push-to-mainnet
#    command: ansible-playbook -i hosts.ini site.yml --limit mainnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"
