steps:
  - name: push-to-sdjnet
    command: ansible-playbook -i hosts.ini playbooks/mainnet.yml --limit sdj01.mainnet.iota.sadj.co
    plugins:
      docker#v1.4.0:
        image: "sadjy/ansible-run" 
        shell: "/bin/sh -e -c"
        mounts:
#          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/vault/orphan_token:/orphan_token   
#        environment:
#          - DOCKER_VAULT_TOKEN
    agents:
      queue: sdj
#  - block: "Block 1"

#    name: push-to-spamnet
#    command: ansible-playbook -i hosts.ini site.yml --limit spamnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"

#  - wait

#  - name: push-to-devnet
#    command: ansible-playbook -i hosts.ini site.yml --limit devnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"

#  - block: "Push to mainnet: confirmation required."
#    prompt: "Push to mainnet?"

#  - name: push-to-mainnet
#    command: ansible-playbook -i hosts.ini site.yml --limit mainnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible
#         shell: "/bin/sh -e -c"
