steps:
  - name: Spamnet run
    command: ansible-playbook -i hosts.ini playbooks/iri-node/iri.yml --extra-vars "iri_img_name=iotacafe/iri-dev iri_img_version=$IRI_BUILD_NUMBER" --limit iri-canary.spamnet --check
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
    agents:
      queue: aws-nano

  - block: "Push to devnet"
    prompt: "Push build $IRI_BUILD_NUMBER to devnet?"

  - name: Devnet run
    command: ansible-playbook -i hosts.ini playbooks/iri-node/iri.yml --extra-vars "iri_img_name=iotacafe/iri-dev iri_img_version=$IRI_BUILD_NUMBER" --limit devnet --check
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
    agents:
      queue: ops-ansible

  - block: "Push to mainnet"
    prompt: "Push build $IRI_BUILD_NUMBER to mainnet?"

  - name: Mainnet run
    command: ansible-playbook -i hosts.ini playbooks/iri-node/iri.yml --extra-vars "iri_img_name=iotacafe/iri-dev iri_img_version=$IRI_BUILD_NUMBER" --limit mainnet --check
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
    agents:
      queue: ops-ansible
