steps:
  - name: Step 1
    command: ls -al && ansible-playbook -i hosts.ini playbooks/iri-node/iri.yml --limit iri02.spamnet.iota.cafe --check
    plugins:
      - docker#v2.0.0:
         image: "sadjy/ansible-run"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
    agents:
      queue: ops
