steps:
  - label: ":linux: Setting up Rust environment and running fmt check"
    command:
      - set -e
      - mkdir /cache/rust
      - apt -qq update && apt -qq install curl ca-certificates gcc pkg-config libssl-dev -y
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain \$RUSTUP_TOOLCHAIN
      - export PATH=\$PATH:\$HOME/.cargo/bin
      - rustup component add rustfmt
      - cargo fmt --all -- --check
    concurrency: 1
    concurrency_group: "Linux"
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "ubuntu:16.04"
        always-pull: false
        environment:
          - CARGO_HOME=/cache/rust/.cargo
          - RUSTUP_HOME=/cache/rust/.rustup
          - PATH=$PATH:/cache/rust/.cargo/bin
          - RUSTUP_TOOLCHAIN=stable
        volumes:
          - /cache-bee-$BUILDKITE_BUILD_ID:/cache
    agents:
      queue: ops

  - wait

  - label: ":linux: Build for Linux platform - nightly"
    command:
      - set -e
      - apt -qq update && apt -qq install curl ca-certificates gcc pkg-config libssl-dev -y
      - rustup toolchain install \$RUSTUP_TOOLCHAIN
      - rustup default \$RUSTUP_TOOLCHAIN
      - cargo build
    concurrency: 1
    concurrency_group: "Linux"
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "ubuntu:16.04"
        always-pull: false
        environment:
          - CARGO_HOME=/cache/rust/.cargo
          - RUSTUP_HOME=/cache/rust/.rustup
          - PATH=$PATH:/cache/rust/.cargo/bin
          - RUSTUP_TOOLCHAIN=nightly
        volumes:
          - /cache-bee-$BUILDKITE_BUILD_ID:/cache
    agents:
      queue: ops

  - wait: ~
    continue_on_failure: true

  - label: ":linux: Build for Linux platform - stable"
    command:
      - set -e
      - apt -qq update && apt -qq install curl ca-certificates gcc pkg-config libssl-dev -y
      - rustup default \$RUSTUP_TOOLCHAIN
      - rustup toolchain list
      - rustc --version
      - cargo test --all
    concurrency: 1
    concurrency_group: "Linux"
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "ubuntu:16.04"
        always-pull: false
        environment:
          - CARGO_HOME=/cache/rust/.cargo
          - RUSTUP_HOME=/cache/rust/.rustup
          - PATH=$PATH:/cache/rust/.cargo/bin
        volumes:
          - /cache-bee-$BUILDKITE_BUILD_ID:/cache
    agents:
      queue: ops

  - label: ":mac: Build for macOS platform -stable"
    command:
      - set -e
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain \$RUSTUP_TOOLCHAIN
      - export PATH=\$PATH:\$HOME/.cargo/bin
			- rustup update
      - rustup toolchain list
      - rustc --version
      - cargo test --all
    concurrency: 1
    concurrency_group: "Mac"
    env: 
      RUSTUP_TOOLCHAIN: stable
    agents:
      queue: mac

  - label: ":windows: Build for Windows platform - stable"
    command:
      - curl -sSf -o rustup-init.exe https://win.rustup.rs
      - rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      - rustup update
			- rustup toolchain list
      - rustc --version
      - cargo test --all
    concurrency: 1
    concurrency_group: "Windows"
    env:
      RUSTUP_TOOLCHAIN: stable
    agents:
      queue: ec2-win-t2medium
