steps:
  - name: build-and-deploy-staging
    command:
      - apt update && apt install jq -y
      - npm i -g --unsafe-perm now
      - now dev --token \$ZEIT_TOKEN --scope iota alias $(now --token \$ZEIT_TOKEN --scope iota deploy --npm -e NODE_ENV=staging -m BK_JOB_ID=$BUILDKITE_JOB_ID) \$ALIAS 
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:8.12-stretch"
         environment:
          - ZEIT_TOKEN
          - ALIAS=website.iota.works
    agents:
      queue: aws-m5large

  - block: "Deploy LIVE"
    prompt: "Deploy this build to prod?"


  - name: build-and-deploy-prod
    command:
      - apt update && apt install jq -y
      - npm i -g --unsafe-perm now
      - now --token \$ZEIT_TOKEN --scope iota alias $(now --token \$ZEIT_TOKEN --scope iota deploy --npm -e NODE_ENV=production -m BK_JOB_ID=$BUILDKITE_JOB_ID) \$ALIAS 
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:8.12-stretch"
         environment:
          - ZEIT_TOKEN
          - ALIAS=iota.org
    agents:
      queue: aws-m5large
