steps:
   - name: build-iri-oracle8
     command: 
        - mvn integration-test -Dlogging-level=INFO && mv target/iri*.jar target/iri-oracle8-PR-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}.jar && java -version && java -version | tee -a build-iri-oracle8-PR-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}.log
#        - mvn versions:set -DnewVersion=$(mvn git-commit-id:revision help:evaluate -Dexpression=project.version | grep -E '^[0-9.]+')-$(git rev-parse --short $BUILDKITE_COMMIT)
     plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "iotacafe/iri-build-env:oracle8u171-1-maven3.5.3-1"
         mounts:
           - /cache/.m2:/root/.m2
     artifact_paths:
       - "target/iri-oracle8-*"
       - docker/entrypoint.sh
       - "build-iri-oracle8-*.log"
       - surefire-reports
       - "*-jvmRun*.dump"
       - "*.dumpstream"
     agents:
       queue: dev

   - wait

   - trigger: iri-push-docker-trusted
     build:
       env:
         ARTIFACT_BUILDKITE_BUILD_ID: $BUILDKITE_BUILD_ID
         IRI_BUILD_NUMBER: PR-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}
         IRI_GIT_COMMIT: $GIT_COMMIT
         IRI_BUILDKITE_PULL_REQUEST_REPO: $BUILDKITE_PULL_REQUEST_REPO
