steps:
  - name: aaa
    command: "exit 0"
    agents:
      queue: ops
    retry:
      automatic: false
      manual: true
  - wait
  - name: bbb
    command: "echo The command passed"
    agents:
      queue: ops