steps:
  - name: 
    command: 'echo {GIT_COMMIT:0:7}-{$BUILDKITE_BUILD_NUMBER}' 
    plugins:
      docker#v1.4.0:
        image: "docker:latest"
        shell: "/bin/sh -e -c"        
    agents:
      queue: sdj

