steps:
  - name: Step 1
    command:
      - pwd 
      - ls -al
      - echo 'aaaa' >> test1.txt
    plugins:
      docker-compose#v2.5.1:
        run: app
        volumes:
          - './workdir:/workdir'
        config:
          - ci-pipelines/iri-regression-tests/docker-compose.yml
    agents:
      queue: sdj



  - name: Step 2
    command:
      - pwd 
      - ls -al
      - cat test1.txt
    plugins:
      docker-compose#v2.5.1:
        run: app
        volumes:
          - './workdir:/workdir'
        config:
          - ci-pipelines/iri-regression-tests/docker-compose.yml
    agents:
      queue: sdj