steps:
  - name: build-documentation-markdown
    command: 
      - |
        rm -rf ci-pipelines
        rm -rf .git
        tar xvfz documentation-markdown.tgz .
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "busybox"
    agents:
      queue: dev
    artifact_paths:
      - "documentation-markdown.tgz"

  - wait

  - trigger: documentation-build-and-deploy
    async: false
    build:
      env:
        DOCS_MARKDOWN_BUILDKITE_BUILD_ID: $BUILDKITE_BUILD_ID
