steps:
  - block: "Publish Release Candidate"
    prompt: "Fill out the details for release"
    fields: 
      - text: "Release Candidate Number"
        key: "release-name"
        hint: "Only digits allowed."

  - name: set-release-metadata
    command: buildkite-agent meta-data set "release-major" "1.6.0"
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "docker:latest"
         shell: "/bin/sh -e -c"
         mount-buildkite-agent: true
    agents:
      queue: ops

