steps:
#  - name: "Cleanup /cache mount"
#    command:
#      - rm -rf /cache/*
#    agents:
#      queue: aws-m5large
#    plugins:
#      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
#        image: "busybox"
#        shell: /bin/sh -c
#        mounts:
#          - /cache-iri-release-$BUILDKITE_BUILD_ID:/cache

#  - wait 

  - name: "Building IRI"
    command:
    - export TAG=$(git describe --tags)
    - |
      if [ -z "$(git show-ref -s $(git describe --tags))" ]
      then
        echo $TAG 
        exit 0
      fi
    - mvn integration-test -Dlogging-level=INFO -log-file integration-test.log && mv target/iri*.jar target/iri-oracle8-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}.jar && java -version && java -version 
    - mkdir /cache/iri && cp target/iri-oracle8-* /cache/iri/
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "iotacafe/iri-build-env:oracle8u171-1-maven3.5.3-1"
        volumes:
          - /cache-iri-release-$BUILDKITE_BUILD_ID:/cache
        environment:
          - TAG
    agents:
      queue: aws-m5large

  - wait

  - name: "Pushing to docker hub"
    command: 
    - mkdir target && cp /cache/iri/iri-oracle8-*.jar target/
    - docker login -u=\$DOCKER_USERNAME -p=\$DOCKER_PASSWORD
    - docker build -t sadjy/iri-dev:\$TAG .
    - docker push sadjy/iri-dev:\$TAG
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "docker"
        mount-buildkite-agent: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /conf/docker/.docker:$HOME/.docker
        - /cache-iri-release-$BUILDKITE_BUILD_ID:/cache
        environment:
          - DOCKER_USERNAME
          - DOCKER_PASSWORD
          - TAG
    agents:
      queue: aws-m5large