steps:
  - name: build-and-push-branch
    command:
    - TAG=$(git describe --tags)
    - |
      if [ ! -z "$(git show-ref -s $(git describe --tags))" ]
      then
        TAG=$(git describe --tags) 
        exit 0
      fi
    - mvn integration-test -Dlogging-level=INFO && mv target/iri*.jar target/iri-oracle8-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}.jar && java -version && java -version | tee -a build-iri-oracle8-${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}.log
    - docker login -u="\$DOCKER_USERNAME" -p="\$DOCKER_PASSWORD"
    - docker build -f $BUILDKITE_PIPELINE_SLUG/Dockerfile -t sadjy/iri-dev:$TAG .
    - docker push sadjy/iri-dev:$TAG
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
        image: "iotacafe/iri-build-env:oracle8u171-1-maven3.5.3-1"
        environment:
          - DOCKER_USERNAME
          - DOCKER_PASSWORD        
    agents:
      queue: aws-m5large


##caution! pushing to official repo, validate the branch is in a good state.
#git push iotaledger dev
##wait for build process to complete
 
#####master###
#git checkout master
#git pull iotaledger master # get master up to date
#git merge -S --no-ff release-v$VERSION
#git log --show-signature -1 #validate signature
#git tag v$VERSION
 
##caution! pushing to official repo, validate the branch is in a good state.
#git push iotaledger v$VERSION #This will run the CI. Wait for it to complete
#git push iotaledger master



