steps:
  - label: ":hammer_and_wrench: Build for macOS platform"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && npm run build && node bugsnag.js"
      - "./node_modules/.bin/electron-builder --mac --x64 --publish=never"
      - "cd out"
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
    agents:
      queue: mac
    artifact_paths:
      - "src/desktop/out/builder-effective-config.yaml"
      - "src/desktop/out/latest*"
      - "src/desktop/out/trinity-desktop*"

  - label: ":hammer_and_wrench: Build for Linux platform"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && npm run build && node bugsnag.js"
      - "./node_modules/.bin/electron-builder --linux --x64 --publish=never"
      - "cd out"
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "node:8.12.0-jessie"
         shell: "/bin/sh -e -c"
    agents:
      queue: dev
    artifact_paths:
      - "src/desktop/out/builder-effective-config.yaml"
      - "src/desktop/out/latest*"
      - "src/desktop/out/trinity-desktop*"

  - label: ":hammer_and_wrench: Build for Windows platform"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "./bugsnag.sh && npm run build && node bugsnag.js"
      - "./node_modules/.bin/electron-builder --win --x64 --publish=never"
      - "cd out"
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
    agents:
      queue: untrusted-windows-vm1
    artifact_paths:
      - "src/desktop/out/builder-effective-config.yaml"
      - "src/desktop/out/latest*"
      - "src/desktop/out/trinity-desktop*"
