steps:
  - name: push-to-sdjnet
    agents:
      queue: sdj
    command: ansible-playbook -i hosts.ini site.yml --limit sdjnet --check 
    plugins:
       docker#v1.4.0:
         image: "sadjy/ansible" 
         mounts:
          - .:/ops-ansible

#  - block: ":dog: woof"

#    name: push-to-spamnet
#    command: ansible-playbook -i hosts.ini site.yml --limit spamnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible

#  - wait

#  - name: push-to-devnet
#    command: ansible-playbook -i hosts.ini site.yml --limit devnet
#    plugins:
#       docker#v1.4.0:
#         image: sadjy/ansible

#  - block: "Push to mainnet: confirmation required."
#    prompt: "Push to mainnet?"

#  - name: push-to-mainnet
#    command: ansible-playbook -i hosts.ini site.yml --limit mainnet
#    plugins:
#       docker#v1.4.0:
#        image: sadjy/ansible