steps:
  - name: push-iri-oracle8
    command: 
      - mkdir -p target docker
      - buildkite-agent artifact download target/iri-oracle8.jar target/ --build $ARTIFACT_BUILDKITE_BUILD_ID
      - buildkite-agent artifact download docker/entrypoint.sh docker/ --build $ARTIFACT_BUILDKITE_BUILD_ID && chmod +x docker/entrypoint.sh
      - docker build -f ci-pipelines/$BUILDKITE_PIPELINE_SLUG/Dockerfile -t iotacafe/iri-dev:$IRI_BUILD_NUMBER .
      - docker push iotacafe/iri-dev:$IRI_BUILD_NUMBER
      - |
        case $IRI_BUILD_NUMBER in
          'PR-'*)
            echo Not pushing to docker hub
            exit 0
          ;;
          *)
            docker tag iotacafe/iri-dev:$IRI_BUILD_NUMBER iotacafe/iri-dev:latest
            docker push iotacafe/iri-dev:latest
          ;;
        esac
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
         image: "docker:latest"
         shell: "/bin/sh -e -c"
         mount-buildkite-agent: true
         mounts:
          - /var/run/docker.sock:/var/run/docker.sock
          - /conf/docker/.docker:$HOME/.docker
    agents:
      queue: ops

  - wait

  - trigger: iri-regression-tests
    build:
      env:
        IRI_BUILD_NUMBER: $IRI_BUILD_NUMBER
        IRI_GIT_COMMIT: $IRI_GIT_COMMIT
        BUILDKITE_PULL_REQUEST_REPO: $BUILDKITE_PULL_REQUEST_REPO
