steps:
  - label: "Pushing to docker hub"
    commands:
      - mkdir target
      - sed -i '1,/# execution image/d' Dockerfile  
      - sed -i 's#--from=local_stage_build /iri/##g' Dockerfile
      - docker login -u=\$DOCKER_USERNAME -p=\$DOCKER_PASSWORD
      - |
        case ${IRI_GIT_TAG:-$IRI_BUILD_NUMBER} in
          *'RELEASE' | *'RC'*)
            buildkite-agent artifact download target/iri-$IRI_VERSION.jar target/ --build $ARTIFACT_BUILDKITE_BUILD_ID
            sha256sum target/iri-$IRI_VERSION.jar | cut -d " " -f 1 > target/SHA256SUM-$IRI_VERSION
            docker build -t iotacafe/iri:$IRI_GIT_TAG -t iotacafe/iri:latest .
            docker push iotacafe/iri:$IRI_GIT_TAG
            docker push iotacafe/iri:latest
            mv target $IRI_VERSION_NUMBER
          ;;
          *)
            buildkite-agent artifact download target/iri-$IRI_BUILD_NUMBER.jar target/ --build $ARTIFACT_BUILDKITE_BUILD_ID
            sha256sum target/iri-$IRI_BUILD_NUMBER.jar | cut -d " " -f 1 > target/SHA256SUM-$IRI_BUILD_NUMBER
            docker build -t iotacafe/iri-dev:$IRI_BUILD_NUMBER -t iotacafe/iri-dev:latest .
            docker push iotacafe/iri-dev:$IRI_BUILD_NUMBER
            docker push iotacafe/iri-dev:latest
            mv target iri-dev
          ;;          
        esac
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "docker"
        always-pull: true
        mount-buildkite-agent: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
    artifact_paths:
      - "${IRI_VERSION_NUMBER:-iri-dev}/iri-${IRI_VERSION:-$IRI_BUILD_NUMBER}.jar"
      - "${IRI_VERSION_NUMBER:-iri-dev}/SHA256SUM-${IRI_VERSION:-$IRI_BUILD_NUMBER}"
    agents:
      queue: aws-m5large

  - wait

  - trigger: iri-regression-tests
    build:
      env:
        IRI_BUILD_NUMBER: $IRI_BUILD_NUMBER
        IRI_GIT_COMMIT: $IRI_GIT_COMMIT
        IRI_BUILDKITE_PULL_REQUEST_REPO: $IRI_BUILDKITE_PULL_REQUEST_REPO
        ARTIFACT_BUILDKITE_BUILD_ID: $ARTIFACT_BUILDKITE_BUILD_ID