steps:
  - label: ":inbox_tray: Download and install dependencies"
    command:
      # Based on https://github.com/why-jay/osx-init/blob/master/install.sh
      # Install Xcode Command Line tools
      - "curl -sL https://raw.githubusercontent.com/timsutton/osx-vm-templates/ce8df8a7468faa7c5312444ece1b977c1b2f77a4/scripts/xcode-cli-tools.sh | bash"
      # Install Homebrew
      - "ruby -e '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'"
      # Install NodeJS and Yarn
      - "brew install node@8 && brew install yarn --without-node"
      # Install Electron
      - "yarn global add electron"
    agents:
      queue: mac

  - wait

  - label: ":hammer_and_wrench: Build for all platforms"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install"
      - "npm run build && electron-builder -mwl"
    artifact_paths:
      - "out/*"
    agents:
      queue: mac
