steps:
  - name: push-to-spamnet-canary
    command: ansible-playbook -i hosts.ini playbooks/iri-node/iri.yml -e iri_img_name=iotacafe/iri-dev -e iri_img_version=latest --limit iri.zeronet
    plugins:
      - https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "iotacafe/ansible-run:latest"
         always-pull: true
         environment:
          - SSH_CLIENT_SIGNER_ADDR
          - SSH_HOST_SIGNER_ADDR
          - DOCKER_VAULT_TOKEN
    agents:
      queue: aws-nano
