steps:
  - label: "Building jar"
    commands:
      - |
        if [[ ! -z "$GIT_TAG" ]]; then 
          mvn versions:set -DnewVersion=$IRI_VERSION
        else
          mvn versions:set -DnewVersion=${BUILDKITE_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}
        fi
      - mvn clean package --log-file build-iri.log
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v3.2.0:
        image: "iotacafe/maven:3.5.4.oracle8u181.1.webupd8.1.1-1"
        always-pull: true
        mount-buildkite-agent: false
        shell: ["/bin/bash", "-e", "-c"]
        volumes:
          - /cache/.m2:/root/.m2
    artifact_paths:
      - "target/iri-*.jar"
      - "target/SHA256SUM-*"
      - "build-iri.log"
    agents:
      queue: dev

  - wait

  - trigger: iri-push-docker-trusted-dev
    build:
      env:
        BUILDKITE_BRANCH: $BUILDKITE_BRANCH
        ARTIFACT_BUILDKITE_BUILD_ID: $BUILDKITE_BUILD_ID
        IRI_BUILD_NUMBER: ${GIT_COMMIT:0:7}-${BUILDKITE_BUILD_ID:0:8}
        IRI_GIT_COMMIT: $GIT_COMMIT
        IRI_GIT_TAG: $GIT_TAG
        IRI_VERSION: $IRI_VERSION
        IRI_VERSION_NUMBER: $IRI_VERSION_NUMBER
        IRI_VERSION_STAGE: $IRI_VERSION_STAGE 