steps:
  - label: ":pipeline: Run Trinity Desktop (PRs) pipeline"
    command:
      - "yarn"
      - "cd src/shared && yarn && cd ../.."
      - "cd src/desktop && npm install && cd ../.."
      - "cd src/shared && yarn audit && cd ../desktop && yarn audit && cd ../.."
      - "yarn lint:shared && yarn lint:desktop"
      - "cd src/desktop && npm run build"
    agents:
      queue: dev
    plugins:
      docker#v1.4.0:
        image: "iotacafe/trinity-desktop-ci:38ef883-8"
