steps:
  - name: "coding style checker"
    command: ./tools/ci_format_check 'cclient consensus gossip mam ciri common cppclient tanglescope'
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - wait
  - name: "TE=1 bazel test opt ASAN"
    command: bazel test -c opt --test_output=all --config asan --define trit_encoding=1 //...
    agents:
      queue: dev
    plugins:
      https://github.com/th0br0/docker-buildkite-plugin#cap_add_2:
        debug: on
        image: "th0br0/iota-buildenv:x86_64"
        capabilities:
          - SYS_PTRACE
        mounts:
          - /conf:/conf
          - /cache:/cache
#  - name: "TE=1 bazel test dbg ASAN"
#    command: bazel test -c dbg --test_output=all --config asan --define trit_encoding=1 //...
#    agents:
#      queue: dev
#    plugins:
#      docker#v1.3.0:
#        image: "th0br0/iota-buildenv:x86_64"
#        mounts:
#          - /conf:/conf
#          - /cache:/cache
  - name: "TE=1 bazel test opt TSAN"
    command: bazel test -c opt --test_output=all --config tsan --define trit_encoding=1 -- //... -//mobile/...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=1 bazel test dbg TSAN"
    command: bazel test -c dbg --test_output=all --config tsan --define trit_encoding=1 -- //... -//mobile/...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=1 bazel test opt UBSAN"
    command: bazel test -c opt --test_output=all --config ubsan --define trit_encoding=1 -- //... -//mobile/...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=1 bazel test dbg UBSAN"
    command: bazel test -c dbg --test_output=all --config ubsan --define trit_encoding=1 -- //... -//mobile/...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - wait
  - name: "TE=3 bazel test opt"
    command: bazel test -c opt --test_output=all --define trit_encoding=3 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=3 bazel test debug"
    command: bazel test -c dbg --test_output=all --define trit_encoding=3 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=4 bazel test opt"
    command: bazel test -c opt --test_output=all --define trit_encoding=4 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=4 bazel test debug"
    command: bazel test -c dbg --test_output=all --define trit_encoding=4 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=5 bazel test opt"
    command: bazel test -c opt --test_output=all --define trit_encoding=5 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "TE=5 bazel test debug"
    command: bazel test -c dbg --test_output=all --define trit_encoding=5 //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "bazel test bootlin x86_64 toolchains"
    command: bazel test --crosstool_top=@iota_toolchains//tools/x86-64-core-i7--glibc--bleeding-edge-2018.07-1:toolchain --cpu=x86_64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "bazel test bootlin i686 toolchains"
    command: bazel test --crosstool_top='@iota_toolchains//tools/x86-i686--glibc--bleeding-edge-2018.07-1:toolchain' --cpu=i686 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //...
    agents:
      queue: dev
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
          - /cache:/cache
